p8105\_hw6\_hh2767
================
Haoran Hu
2018-11-22

Problem 1
=========

Read and describe the dataset
-----------------------------

``` r

homicide = GET("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  content("raw") %>% 
  read_csv()
## Parsed with column specification:
## cols(
##   uid = col_character(),
##   reported_date = col_integer(),
##   victim_last = col_character(),
##   victim_first = col_character(),
##   victim_race = col_character(),
##   victim_age = col_character(),
##   victim_sex = col_character(),
##   city = col_character(),
##   state = col_character(),
##   lat = col_double(),
##   lon = col_double(),
##   disposition = col_character()
## )

str(homicide)
## Classes 'tbl_df', 'tbl' and 'data.frame':    52179 obs. of  12 variables:
##  $ uid          : chr  "Alb-000001" "Alb-000002" "Alb-000003" "Alb-000004" ...
##  $ reported_date: int  20100504 20100216 20100601 20100101 20100102 20100126 20100127 20100127 20100130 20100210 ...
##  $ victim_last  : chr  "GARCIA" "MONTOYA" "SATTERFIELD" "MENDIOLA" ...
##  $ victim_first : chr  "JUAN" "CAMERON" "VIVIANA" "CARLOS" ...
##  $ victim_race  : chr  "Hispanic" "Hispanic" "White" "Hispanic" ...
##  $ victim_age   : chr  "78" "17" "15" "32" ...
##  $ victim_sex   : chr  "Male" "Male" "Female" "Male" ...
##  $ city         : chr  "Albuquerque" "Albuquerque" "Albuquerque" "Albuquerque" ...
##  $ state        : chr  "NM" "NM" "NM" "NM" ...
##  $ lat          : num  35.1 35.1 35.1 35.1 35.1 ...
##  $ lon          : num  -107 -107 -107 -107 -107 ...
##  $ disposition  : chr  "Closed without arrest" "Closed by arrest" "Closed without arrest" "Closed by arrest" ...
##  - attr(*, "spec")=List of 2
##   ..$ cols   :List of 12
##   .. ..$ uid          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ reported_date: list()
##   .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
##   .. ..$ victim_last  : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ victim_first : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ victim_race  : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ victim_age   : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ victim_sex   : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ city         : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ state        : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   .. ..$ lat          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ lon          : list()
##   .. .. ..- attr(*, "class")= chr  "collector_double" "collector"
##   .. ..$ disposition  : list()
##   .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
##   ..$ default: list()
##   .. ..- attr(*, "class")= chr  "collector_guess" "collector"
##   ..- attr(*, "class")= chr "col_spec"
```

The raw dataset contains 12 variables and 52179 observations. It contains information about 52179 homicides occured in the US. The variables in this dataset are:

-   uid: homicide id
-   reported\_date: reported date
-   victim\_last: last name of victim
-   victim\_first: first name of victim
-   victim\_race: race of victim
-   victim\_age: age of victim
-   victim\_sex: sex of victim
-   city: city of the homicides
-   state: state of the homicides
-   lat: occurrence latitude
-   lon: occurence longitude
-   disposition: result of investigation

The location, time, and information of victims of each homicide are included in the dataset. The dataset also indicates whether the homicides are solved or not.

Adding variables and tidying the dataset
----------------------------------------

In the following part, I will:

-   create a sity\_state variable which show the city and state of occurence

-   add a binary variable indicating whether the homicide is solved

-   omit cities Dallas, TX; Phoenix, AZ; Kansas City, MO; and Tulsa, AL

-   modifiy victim\_race to have categories white and non-white, with white as the reference category

-   change victim\_age to numeric variable

``` r
homicide = homicide %>% 
  mutate(city_state = str_c(city, ",", state),
         resolved = as.numeric(disposition == "Closed by arrest"),
         victim_race = as.factor(ifelse(victim_race == "White", "white", "non-white")),
         victim_race = relevel(victim_race, ref = "white"),
         victim_age = as.numeric(victim_age)
         ) %>%
  filter(!city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")) 
## Warning in evalq(as.numeric(victim_age), <environment>): 强制改变过程中产生
## 了NA

str(homicide)
## Classes 'tbl_df', 'tbl' and 'data.frame':    48507 obs. of  14 variables:
##  $ uid          : chr  "Alb-000001" "Alb-000002" "Alb-000003" "Alb-000004" ...
##  $ reported_date: int  20100504 20100216 20100601 20100101 20100102 20100126 20100127 20100127 20100130 20100210 ...
##  $ victim_last  : chr  "GARCIA" "MONTOYA" "SATTERFIELD" "MENDIOLA" ...
##  $ victim_first : chr  "JUAN" "CAMERON" "VIVIANA" "CARLOS" ...
##  $ victim_race  : Factor w/ 2 levels "white","non-white": 2 2 1 2 1 1 2 2 1 2 ...
##  $ victim_age   : num  78 17 15 32 72 91 52 52 56 43 ...
##  $ victim_sex   : chr  "Male" "Male" "Female" "Male" ...
##  $ city         : chr  "Albuquerque" "Albuquerque" "Albuquerque" "Albuquerque" ...
##  $ state        : chr  "NM" "NM" "NM" "NM" ...
##  $ lat          : num  35.1 35.1 35.1 35.1 35.1 ...
##  $ lon          : num  -107 -107 -107 -107 -107 ...
##  $ disposition  : chr  "Closed without arrest" "Closed by arrest" "Closed without arrest" "Closed by arrest" ...
##  $ city_state   : chr  "Albuquerque,NM" "Albuquerque,NM" "Albuquerque,NM" "Albuquerque,NM" ...
##  $ resolved     : num  0 1 0 1 0 0 1 1 0 0 ...
```

Logistic regression for Baltimore
---------------------------------

In this part, I will:

-   Focus on the city of Baltimore, MD

-   use the glm function to fit a logistic regression with resolved vs unresolved as the outcome and victim age, sex and race (as just defined) as predictors

-   save the output of glm as an R object

-   apply the broom::tidy to this object; and obtain the estimate and confidence interval of the adjusted odds ratio for solving homicides comparing non-white victims to white victims keeping all other variables fixed

``` r
baltimore_logistic = 
  homicide %>% 
  filter(city == "Baltimore") %>%
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())

race_OR = baltimore_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>% 
  merge(., 
        exp(confint(baltimore_logistic)) %>% broom::tidy(), 
        by.x = "term", by.y = ".rownames") %>% 
  filter(term == "victim_racenon-white") %>% 
  mutate(city = "Baltimore, MD") %>% 
  select(city, OR, CI_lower = X2.5.., CI_upper = X97.5..) 
## Waiting for profiling to be done...
## Warning: 'tidy.matrix' is deprecated.
## See help("Deprecated")


baltimore_race_OR = baltimore_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>% 
  cbind(., 
        exp(baltimore_logistic %>% 
  broom::confint_tidy())) %>% 
  filter(term == "victim_racenon-white") %>% 
  mutate(city = "Baltimore, MD") %>% 
  select(city,term, OR, '95% conf.low' = conf.low, '95% conf.high' = conf.high) 

baltimore_race_OR %>% 
  knitr::kable(digits = 3)
```

| city          | term                  |     OR|  95% conf.low|  95% conf.high|
|:--------------|:----------------------|------:|-------------:|--------------:|
| Baltimore, MD | victim\_racenon-white |  0.441|         0.312|           0.62|

The table above shows the estimate and confidence interval of the adjusted odds ratio for solving homicides comparing non-white victims to white victims keeping all other variables fixed. The estimated adjusted odds ratio is 0.441, which means that the murdered non-white people have 0.441 times the odds of having the homicide solved when compared with white people. The 95% confidence interval for the adjusted OR is \[0.312, 0.62\]
